### ISSUE TITLE
How to build the project

### ISSUE THREAD

**Issue by FuncJ** [icl-utk-edu/plasma#12]
Hi, Could you please tell me how to build plasma? Where can I find the relevant documentation？Specifically, I have the following questions：
1 Should Plasma link to the single-threaded BLIS library？
2 Does Plasma need to set ‘USE_LAPACK=ON’ when linking to Openblas？
3 Is the subroutine 'plasma_dsgesv' used to solve double precision linear equations? How about single precision?

**Comment by luszczek** [comment]
I added in commit 22bfa15e a few paragraphs on installation of PLASMA to the README.md file in the repo.

For double precision, use `plasma_dgesv()`, for single precision: `plasma_sgesv()`, and for double precision with low condition numbers use `plasma_dsgesv()` which will mix precisions for a faster solve.
