### ISSUE TITLE
Plasma won't build with gcc 11 and openblas

### ISSUE THREAD

**Issue by bgeneto** [icl-utk-edu/plasma#20]
Can't build plasma using gcc 11 and openblas. Steps and errors messages follows: 

````bash
git clone https://github.com/icl-utk-edu/plasma.git
cd plasma/
make  # selected gcc, gfortran, and openblas
```` 

First error while making:

````
compute/zlaneg2.c:95:20: error: unknown type name ‘plasma_complex64_t’
95 | int plasma_zlaneg2(plasma_complex64_t *diag, plasma_complex64_t *offd, int n, plasma_complex64_t u) {
```` 

Added the required plasma header files to `zlaneg2.c` and issued `make` again:

```
compute/zlaneg2.c:111:15: error: invalid operands to binary < (have ‘plasma_complex64_t’ {aka ‘_Complex double’} and ‘int’)
111 |     if (Pm1_0 < 0) isneg = 1;  /* our first test. */
```

Now I've deleted the offending file (`zlaneg2.c`) and tried to continue the `make` process: 

```
compute/zstevx2.c:156:18: error: invalid operands to binary < (have ‘plasma_complex64_t’ {aka ‘_Complex double’} and ‘plasma_complex64_t’ {aka ‘_Complex double’})
  156 |         if (test < min) {
      |                  ^
```

So I ended up giving up... Is plasma still maintained or was it replaced by another project/library? TIA.

**Comment by FuncJ** [comment]
> Can't build plasma using gcc 11 and openblas. Steps and errors messages follows:
> 
> ```shell
> git clone https://github.com/icl-utk-edu/plasma.git
> cd plasma/
> make  # selected gcc, gfortran, and openblas
> ```
> 
> First error while making:
> 
> ```
> compute/zlaneg2.c:95:20: error: unknown type name ‘plasma_complex64_t’
> 95 | int plasma_zlaneg2(plasma_complex64_t *diag, plasma_complex64_t *offd, int n, plasma_complex64_t u) {
> ```
> 
> Added the required plasma header files to `zlaneg2.c` and issued `make` again:
> 
> ```
> compute/zlaneg2.c:111:15: error: invalid operands to binary < (have ‘plasma_complex64_t’ {aka ‘_Complex double’} and ‘int’)
> 111 |     if (Pm1_0 < 0) isneg = 1;  /* our first test. */
> ```
> 
> Now I've deleted the offending file (`zlaneg2.c`) and tried to continue the `make` process:
> 
> ```
> compute/zstevx2.c:156:18: error: invalid operands to binary < (have ‘plasma_complex64_t’ {aka ‘_Complex double’} and ‘plasma_complex64_t’ {aka ‘_Complex double’})
>   156 |         if (test < min) {
>       |                  ^
> ```
> 
> So I ended up giving up... Is plasma still maintained or was it replaced by another project/library? TIA.

I have the same problem with you. Are there any other libs to solve linear system problems?

**Comment by MoiseRousseau** [comment]
I'm on Ubuntu 22.04 LTS with GCC 11.2.0 and OpenBLAS. I successfully installed PLASMA (latest version) with CMake:
```
mkdir build && cd build
cmake ..
make
```
However, I had to change the LAPACKE_LIBRAIRIES variable in CMake as it pointed to OpenBLAS and not LAPACKE, creating errors when linking. Line 86 of the CMakeLists.txt, add the following (you may have to ajust and find yourself the location of `liblapacke.so`):
`set(LAPACKE_LIBRARIES "/usr/lib/x86_64-linux-gnu/liblapacke.so")`
