### ISSUE TITLE
Unable to locate files from the repo

### ISSUE THREAD

**Issue by rahulurms** [icl-utk-edu/plasma#31]
I get the errors below when I am trying to build the PLASMA library.
 
CMake Error at CMakeLists.txt:329 (add_library):
  Cannot find source file:
    core_blas/core_scabs1.c

CMake Error at CMakeLists.txt:189 (add_library):
  Cannot find source file:
    compute/scamax.c

CMake Error at CMakeLists.txt:396 (add_executable):
  Cannot find source file:
    test/test_damax.c

If the files are not in the repository, why are they mentioned in the CMakeLists.txt? 

Can someone suggest me the appropriate steps to build PLASMA library?

**Comment by weilinscenccs** [comment]
try release the tar, not use the repo.

**Comment by luszczek** [comment]
This has been fixed with commit 655aa33df8a13a97a78d5c05544f7ef6c646bbc4
