### ISSUE TITLE
Plasma user google group is a broken link?

### ISSUE THREAD

**Issue by Phylloxera** [icl-utk-edu/plasma#34]
When I click on the link in the README, I get 'Content unavailable'. Has PLASMA been replaced by MAGMA?

**Comment by luszczek** [comment]
Not sure which link gives`content unavailable` message but the forum in Google Groups definitely works for me. I only update the download link in eeac1f2 just now.

**Comment by Phylloxera** [comment]
I apologize for not including the link in the body. This is the link from the README: https://groups.google.com/a/icl.utk.edu/forum/#!forum/plasma-user
I've attached a screenshot with the error I've received in 3 different browsers.
<img width="973" alt="Screenshot 2024-05-16 at 7 48 16 AM" src="https://github.com/icl-utk-edu/plasma/assets/13121075/4d51c86a-b535-4cd6-9591-aae86f3947e9">

**Comment by luszczek** [comment]
The group requires a sign up for new members. The settings were setup to make the group not viewable by default. But you screenshot clearly shows the link works and the group is there.

**Comment by Phylloxera** [comment]
Thanks for the reply, @luszczek Can I join the PLASMA group? Where do I sign up? I was able to join the MAGMA group (there was a Join Group button, I think). There does not seem to be such an option for the PLASMA group.

**Comment by mgates3** [comment]
I fixed the PLASMA email list settings so there should be an "Ask to join group" button. You must be logged into a Google account (not necessarily a Gmail account). If you're not logged into a Google account, the button will say "Contact owners and managers" instead.

@luszczek "Who can see group" needs to be "Anyone on the web" (a bit like `chmod a+x`), in order for the "Who can join group" option "Anyone on the web can ask" to display the join button. There's a separate "Who can view conversations" setting, which was already set to "Anyone on the web" (like `chmod a+r`), if we want only group members to see messages.

**Comment by Phylloxera** [comment]
Thanks @luszczek and @mgates3 ! When I clicked on the link in safari browser this morning, I was redirected to my list of Google Groups. But when I copied / pasted the link into my browser, I got the "Ask to join group" button available and was able to submit the request.

**Comment by luszczek** [comment]
I've added you to PLASMA user group on Google Groups and I enabled PLASMA discussions here on Github so you can easily linked to your issues or pull requests
