### ISSUE TITLE
Plasma won't build with gcc 14 and openblas

### ISSUE THREAD

**Issue by selphie-til** [icl-utk-edu/plasma#36]
I have tried to build the PLASMA library version 23.8.2, but I get the following error and will not proceed.

Is there a solution to this problem?

`mkdir build`
`cmake ..`

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Found BLAS libraries /opt/OpenBLAS
-- Found LAPACK libraries libopenblas_seq
-- Found OpenBLAS 0.3.26
-- BLAS(TRUE)
-- LAPACK(TRUE)
-- Found Generic BLAS
-- vendor `All', linker flags `'
CMake Error at CMakeLists.txt:118 (message):
  CBLAS_TRANSPOSE missing as defined type or enumeration type

-- Configuring incomplete, errors occurred!

**Comment by luszczek** [comment]
There is very information I can see from the information provided. Looks like there is an issue with your OpenBLAS because it is reported as `Generic BLAS`. Perhaps fixing the installation could help. Otherwise, I would need more information about your system, BLAS, and other info available in CMake output files.

**Comment by selphie-til** [comment]
Thank you for your response.
What other information do you need?
For now, I attach the CMakeCache.txt file output by cmake.
[CMakeCache.txt](https://github.com/user-attachments/files/15938256/CMakeCache.txt)
In addition, I also attach the Makefile.rule for OpenBLAS build.
[Makefile.txt](https://github.com/user-attachments/files/15938263/Makefile.txt)

**Comment by luszczek** [comment]
Based on the files you provided, I suggest to give more information to CMake on your command line:

```sh
cmake -D BLAS_LIBRARIES=/opt/OpenBLAS/lib/libopenblas*.so -D LAPACK_LIBRARIES=/opt/OpenBLAS/lib/lib*.so ..
```
I think your OpenBLAS library is called `/opt/OpenBLAS/lib/libopenblas_seq-r0.3.26.so` but I used a wildcard with `*` to catch other possibilities.

I tested the above line on my system and it worked. I don't have access to modify `/opt` so my paths differ but the build worked with GNU GCC 13.2 and OpenBLAS 3.24.0. You should be able to adjust it to your system needs.

**Comment by selphie-til** [comment]
Based on your advice, I executed the following commands.
`cmake -DBLAS_LIBRARIES=/opt/OpenBLAS/lib/libopenblas_seq_haswell-r0.3.26.so -D LAPACK_LIBRARLIES=/opt/OpenBLAS/lib/libopenblas_seq_haswell-r0.3.26.so ..`

Then I was stumped by the following error the next time.

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 14.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found BLAS: /opt/OpenBLAS/lib/libopenblas_seq_haswell-r0.3.26.so  
-- Found BLAS libraries /opt/OpenBLAS/lib/libopenblas_seq_haswell-r0.3.26.so
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found LAPACK: /opt/OpenBLAS/lib/libopenblas_seq_haswell-r0.3.26.so;-lm;-ldl  
-- Found LAPACK libraries /opt/OpenBLAS/lib/libopenblas_seq_haswell-r0.3.26.so;-lm;-ldl
-- Found OpenBLAS 0.3.26
-- BLAS(TRUE)
-- LAPACK(TRUE)
-- Found OpenBLAS
-- Found OpenBLAS: /opt/OpenBLAS/include  
-- Found CBLAS: /opt/OpenBLAS/include  
-- Found LAPACKE: /opt/OpenBLAS/include  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done (0.5s)
CMake Error at CMakeLists.txt:329 (add_library):
  Cannot find source file:

    core_blas/core_scabs1.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:396 (add_executable):
  Cannot find source file:

    test/test_damax.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:329 (add_library):
  No SOURCES given to target: plasma_core_blas


CMake Error at CMakeLists.txt:396 (add_executable):
  No SOURCES given to target: plasmatest


CMake Generate step failed.  Build files cannot be regenerated correctly.

[CMakeCache.txt](https://github.com/user-attachments/files/15938369/CMakeCache.txt)

Indeed, it seems that there is only double precision complex source code under core_blas.

**Comment by luszczek** [comment]
There is something strange about your setup because the first line of `CMakeLists.txt` in PLASMA repo says:

```cmake
cmake_minimum_required( VERSION 3.12 FATAL_ERROR )
```

Your output indicates a much older version.

The missing files indicate another issue in your setup: you're missing source code that is auto-generated during configuration. But this is done for you on line 24 of `CMakeLists.txt`: `execute_process(COMMAND "${Python_EXECUTABLE}" ...`.

I have no idea where you obtained the PLASMA code and how you changed it. A fresh `clone` of the repo or a hard `reset` should fix it.

**Comment by selphie-til** [comment]
I have reacquired it in the following way.
`git clone https://github.com/icl-utk-edu/plasma.git`
`cd plasma`
`git checkout -b 23.8.2 refs/tags/23.8.2 `

However, the same error is output.

My version of cmake is as follows.
`cmake --version`
cmake version 3.28.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

If I run cmake, does that mean that the source code for single precision, etc. will be generated automatically?

**Comment by luszczek** [comment]
If you want to use old version of PLASMA then you need to downgrade your tools like CMake.

If you use the HEAD (don't run `checkout`) then you'll get all the new features that will help you make it work on your system.

I have no idea why you create a branch for version 23.8.2 either.

**Comment by selphie-til** [comment]
I worked on the main branch and it worked fine.
Thanks for your advice.
